name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permission for Gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Download dependencies using Gradle
      - name: Download Dependencies
        run: ./gradlew dependencies

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Run UI Tests
      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      # Build APK (Debug or Release)
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload the APK as an artifact to download it later
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
